# https://github.com/dart-lang/lints#migrating-from-packagepedantic
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - example/**/*.dart
  language:
    strict-casts: true
linter:
  rules:
    overridden_fields: false
    avoid_print: true  # Uncomment to disable the `avoid_print` rule
    always_declare_return_types: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unawaited_futures: true
    unsafe_html: true
    use_full_hex_values_for_flutter_colors: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_parenthesis: true
