name: artemis
version: 7.13.0-beta.2

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  build_config: ^1.1.2
  code_builder: ^4.10.1
  build: ^2.4.2
  collection: ^1.19.1
  dart_style: ^3.0.1
  equatable: ^2.0.7
  glob: ^2.1.3
  gql_code_builder: ^0.13.1
  gql_dedupe_link: ^2.0.3+1
  gql_exec: ^1.0.0+1
  gql_http_link: ^1.1.0
  gql_link: ^1.0.0+1
  gql: ^1.0.0+1
  http: ^1.3.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  pub_semver: ^2.1.5
  recase: ^4.1.0
  source_gen: ^2.0.0
  yaml: ^3.1.3

dev_dependencies:
  args: ^2.6.0
  build_runner: ^2.4.15
  build_test: ^2.2.3
  build_resolvers: ^2.4.4
  json_serializable: ^6.9.4
  logging: ^1.3.0
  lints: ^5.1.1
  test: ^1.25.15
