name: dartpollo_workspace
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - packages/dartpollo
  - packages/dartpollo_annotation
  - packages/dartpollo_generator

dev_dependencies:
  melos: ^7.5.0

melos:
  sdkPath: .fvm/flutter_sdk
  scripts:
    analyze:
      run: fvm dart analyze --fatal-infos
      exec:
        concurrency: 3
    test:
      run: fvm dart test
      exec:
        concurrency: 1
    format:
      run: fvm dart format .
    pub-get:
      run: fvm flutter pub get
