name: dartpollo_workspace
publish_to: none

environment:
  sdk: ^3.12.1

workspace:
  - packages/dartpollo
  - packages/dartpollo_annotation
  - packages/dartpollo_generator

dev_dependencies:
  melos: ^7.8.1

melos:
  sdkPath: .fvm/flutter_sdk
  scripts:
    analyze:
      run: dart analyze --fatal-infos
      exec:
        concurrency: 3
    test:
      run: dart test
      exec:
        concurrency: 1
    format:
      run: dart format packages/
