targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - pokemon.schema.graphql
    builders:
      dartpollo_generator|dartpollo:
        options:
          optimize_document_nodes: true
          use_graphql_data_class: true
          fragments_glob: graphql/**.fragment.graphql
          schema_mapping:
            - schema: pokemon.schema.graphql
              queries_glob: graphql/simple_query.query.graphql
            - schema: pokemon.schema.graphql
              queries_glob: graphql/big_query.query.graphql
            - schema: pokemon.schema.graphql
              queries_glob: graphql/fragment_query.query.graphql
            - schema: pokemon.schema.graphql
              queries_glob: graphql/fragments_glob.query.graphql
