on: pull_request

name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.9.2
      - uses: bluefireteam/melos-action@v3
      - name: Check formatting
        run: dart format --set-exit-if-changed packages/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.9.2
      - uses: bluefireteam/melos-action@v3
      - name: Test
        run: melos run test

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.9.2
      - uses: bluefireteam/melos-action@v3
      - name: Analyze
        run: melos run analyze
